title: PL Conference Deadlines
description: Countdowns to top PL venue deadlines
author: Yichen Xu

domain: "www.emanueledosualdo.com"
baseurl: "/pl-deadlines"

github_username: bordaigorl
github_repo: pl-deadlines

markdown: kramdown
ga_id:

include: ['_pages']

repository: linyxus/pl-deadlines

